osaf: Fix compilation errors when building with GCC 4.9.0 [#883]
OpenSAF did not build successfully with GCC 4.9.0, due to a new warning:

In file included from ncs_sprr.c:37:0:
ncs_sprr.c: In function 'ncs_splr_api':
../../../../osaf/libs/core/include/ncssysf_def.h:105:54: error: right-hand operand of comma expression has no effect [-Werror=unused-value]
 #define m_LEAP_DBG_SINK(r) (TRACE("IN LEAP_DBG_SINK"), r)
                                                      ^
ncs_sprr.c:46:58: note: in expansion of macro 'm_LEAP_DBG_SINK'
 #define m_NCS_SPRR_DBG_SINK(x,y)  printf("SPRR:%s\n", y),m_LEAP_DBG_SINK(x)
                                                          ^
ncs_sprr.c:237:9: note: in expansion of macro 'm_NCS_SPRR_DBG_SINK'
    rc = m_NCS_SPRR_DBG_SINK(NCSCC_RC_DUPLICATE_ENTRY, "SPLR duplication attempted");

The warning actually pointed out a rather tricky bug in ncs_sprr.c, that is not
obvious the first time you look at the code. The bug is that the comma operator
is used within a C preprocessor macro, without surrounding parentheses. When
this macro is used in an assignment statement, the code does not do what you
would expect, since the comma operator has lower precedence than the assignment
operator in the C language.

By adding parentheses around the macro definition, this bug is solved.